require("dotenv").config()
const express = require("express")
const bodyparser = require("body-parser")
const passport = require("passport")
const passportConfig=require("./Users/passportConfig")
const userRouter = require("./Users/users")
const feedRouter=require("./Posts/posts")
const path=require("path")
const dbStart=require("./DBstart")
const app=express();
dbStart.dbConnect(()=>{app.listen(3000);console.log("server spinned up")})
app.get("/",(req,res,next)=>{res.sendFile(path.join(__dirname,"Views","index.html"))})
app.get('/users',(req,res)=>{res.sendFile(path.join(__dirname,"Views","users.html"))})
app.use(bodyparser.json())
app.use(bodyparser.urlencoded({extended:false}))
app.use(passport.initialize())
passport.use(passportConfig.strategy)
app.use("/users",userRouter)
app.use("/feed",feedRouter)